image_params:
  dark_threshold: 50
  light_threshold: 220

blur:
  not_usable:
    values:
      score_blurredness: 0.1
    message: |
      Изображение не может быть обработано из-за сильного размытия. 
      Пожалуйста, повторите сканирование с улучшенной фокусировкой.
  high:
    values:
      score_blurredness: 0.3
    message: |
      Изображение сильно размыто.
      Рекомендуется повторное сканирование с улучшенной фокусировкой. 
      При обработке используйте методы восстановления изображений 
      (деконволюция, алгоритмы увеличения резкости Richardson-Lucy).
  medium:
    values:
      score_blurredness: 0.6
    message: |
      Изображение имеет среднюю степень размытия. 
      Примените фильтр увеличения резкости (Unsharp Mask) 
      с параметрами: amount=1.5, radius=1, threshold=0.
  low:
    values:
      score_blurredness: 0.95 
    message: |
      Размытие в пределах нормы.

overexposure:
  not_usable:
    values:
      score_contrast: 0.1
      score_luminosity: 0.95
    message: |
      Изображение не может быть обработано из-за сильной передержки. 
      Пожалуйста, повторите сканирование с уменьшенной яркостью.
  high:
    values:
      score_contrast: 0.3
      score_luminosity: 0.95
    message: |
      Изображение имеет сильную передержку. 
      Требуется повторное сканирование с уменьшенной яркостью. 
      При постобработке используйте алгоритмы восстановления деталей 
      в пересвеченных областях (HDR Tone mapping).
  medium:
    values:
      score_contrast: 0.6
      score_luminosity: 0.95
    message: |
      Изображение имеет среднюю передержку. 
      Примените коррекцию уровней, уменьшив общую яркость 
      и увеличив контраст в средних тонах.
  low:
    values:
      score_contrast: 0.95
      score_luminosity: 0.95
    message: |
      Изображение имеет легкую передержку.

underexposure:
  not_usable:
    values:
      score_contrast: 0.1
      score_luminosity: 0.1
    message: |
      Изображение не может быть обработано из-за сильной недодержки. 
      Пожалуйста, повторите сканирование с увеличенной яркостью.
  high:
    values:
      score_contrast: 0.5
      score_luminosity: 0.3
    message: |
      Изображение имеет критическую недодержку. 
      Требуется повторное сканирование с увеличенной яркостью. 
      При постобработке используйте алгоритмы локальной адаптивной коррекции яркости.
  medium:
    values:
      score_contrast: 0.7
      score_luminosity: 0.6
    message: |
      Изображение имеет среднюю недодержку.
      Примените адаптивную коррекцию яркости (CLAHE) 
      с параметром clipLimit=2.0, tileGridSize=(8,8).
  low:
    values:
      score_contrast: 0.95
      score_luminosity: 0.95
    message: |
      Изображение имеет легкую недодержку.
      Рекомендуется повысить яркость на 10-15% и увеличить контраст в светах.




noise:
  salt_pepper:
    not_usable:
      values:
        sharpness: 70000.0
        entropy: 0.1
        ssim: 0.4
      message: |
        Изображение не может быть обработано из-за сильного шума 'соль и перец'. 
        Пожалуйста, повторите сканирование с очисткой поверхности.
    high:
      values:
        sharpness: 50000.0
        ssim: 0.45
        entropy: 0.1
      message: |
        Изображение имеет сильный шум типа 'соль и перец'. 
        Рекомендуется повторное сканирование с очисткой поверхности. 
        При постобработке примените медианный фильтр с размером ядра 3x3 или 5x5.
    medium:
      values:
        sharpness: 25000.0
        ssim: 0.65
        entropy: 0.1
      message: |
        Изображение имеет умеренный шум типа 'соль и перец'. 
        Попробуйте медианный фильтр 3x3.
    low:
      values:
        sharpness: 10000.0
        ssim: 0.85
        entropy: 0.1
      message: |
        Шум 'соль и перец' незначителен.
    
  gaussian:
    not_usable:
      values:
        contrast: 0.10
        dark_ratio: 0
        ssim: 1.0
      message: |
        Изображение не может быть обработано из-за сильного гауссового шума. 
        Пожалуйста, повторите сканирование с улучшенной очисткой поверхности.
    high:
      values:
        contrast: 0.15
        dark_ratio: 0
        ssim: 1.0
      message: |
        Изображение имеет гауссов шум средней интенсивности. 
        Примените билатеральный фильтр (d=5, sigmaColor=75, sigmaSpace=75) 
        или нелокальное усреднение для сохранения деталей при шумоподавлении.
    medium:
      values:
        contrast: 0.20
        dark_ratio: 0
        ssim: 1.0
      message: |
        Изображение имеет умеренный гауссов шум. 
        Используйте методы мягкого шумоподавления.
    low:
      values:
        contrast: 0.25
        dark_ratio: 0
        ssim: 1.0
      message: |
        Гауссов шум незначителен.



