image_params:
  dark_threshold: 50
  light_threshold: 220

blur:
  high:
    values:
      sharpness: 240.0
    message: |
      Изображение сильно размыто.
      Рекомендуется повторное сканирование с улучшенной фокусировкой. 
      При обработке используйте методы восстановления изображений 
      (деконволюция, алгоритмы увеличения резкости Richardson-Lucy).
  medium:
    values:
      sharpness: 800.0
    message: |
      Изображение имеет среднюю степень размытия. 
      Примените фильтр увеличения резкости (Unsharp Mask) 
      с параметрами: amount=1.5, radius=1, threshold=0.
  low:
    values:
      sharpness: 1200.0  # Примерное значение, скорректируйте при необходимости
    message: |
      Размытие в пределах нормы.
  not_usable:
    values:
      sharpness: 0.0
    message: |
      Изображение не может быть обработано из-за сильного размытия. 
      Пожалуйста, повторите сканирование с улучшенной фокусировкой.
noise:
  salt_pepper:
    high:
      values:
        sharpness: 15000.0
        entropy: 0.5
      message: |
        Изображение имеет сильный шум типа 'соль и перец'. 
        Рекомендуется повторное сканирование с очисткой поверхности. 
        При постобработке примените медианный фильтр с размером ядра 3x3 или 5x5.
    medium:
      values:
        sharpness: 8000.0
        entropy: 0.5
      message: |
        Изображение имеет умеренный шум типа 'соль и перец'. 
        Попробуйте медианный фильтр 3x3.
    low:
      values:
        sharpness: 3000.0
        entropy: 0.5
      message: |
        Шум 'соль и перец' незначителен.
    not_usable:
      values:
        sharpness: 0.0
        entropy: 0.5
      message: |
        Изображение не может быть обработано из-за сильного шума 'соль и перец'. 
        Пожалуйста, повторите сканирование с очисткой поверхности.
  gaussian:
    high:
      values:
        sharpness: 5000.0
        entropy: 0.5
      message: |
        Изображение имеет гауссов шум средней интенсивности. 
        Примените билатеральный фильтр (d=5, sigmaColor=75, sigmaSpace=75) 
        или нелокальное усреднение для сохранения деталей при шумоподавлении.
    medium:
      values:
        sharpness: 2000.0
        entropy: 0.5
      message: |
        Изображение имеет умеренный гауссов шум. 
        Используйте методы мягкого шумоподавления.
    low:
      values:
        sharpness: 800.0
        entropy: 0.5
      message: |
        Гауссов шум незначителен.
    not_usable:
      values:
        sharpness: 0.0
        entropy: 0.0
      message: |
        Изображение не может быть обработано из-за сильного гауссового шума. 
        Пожалуйста, повторите сканирование с улучшенной очисткой поверхности.

overexposure:
  high:
    values:
      light_ratio: 0.9078
      dark_ratio: 0.02
    message: |
      Изображение имеет сильную передержку. 
      Требуется повторное сканирование с уменьшенной яркостью. 
      При постобработке используйте алгоритмы восстановления деталей 
      в пересвеченных областях (HDR Tone mapping).
  medium:
    values:
      light_ratio: 0.90068
      dark_ratio: 0.03
    message: |
      Изображение имеет среднюю передержку. 
      Примените коррекцию уровней, уменьшив общую яркость 
      и увеличив контраст в средних тонах.
  low:
    values:
      light_ratio: 0.89
      dark_ratio: 0.044
    message: |
      Изображение имеет легкую передержку. 
      Рекомендуется применить небольшую коррекцию 
      экспозиции (-0.3EV) и увеличить контраст в тенях.
  not_usable:
    values:
      light_ratio: 0.0
      dark_ratio: 0.0
    message: |
      Изображение не может быть обработано из-за сильной передержки. 
      Пожалуйста, повторите сканирование с уменьшенной яркостью.

underexposure:
  high:
    values:
      dark_ratio: 0.08
    message: |
      Изображение имеет критическую недодержку. 
      Требуется повторное сканирование с увеличенной яркостью. 
      При постобработке используйте алгоритмы локальной адаптивной коррекции яркости.
  medium:
    values:
      dark_ratio: 0.055
    message: |
      Изображение имеет среднюю недодержку.
      Примените адаптивную коррекцию яркости (CLAHE) 
      с параметром clipLimit=2.0, tileGridSize=(8,8).
  low:
    values:
      dark_ratio: 0.045
    message: |
      Изображение имеет легкую недодержку.
      Рекомендуется повысить яркость на 10-15% и увеличить контраст в светах.
  not_usable:
    values:
      dark_ratio: 0.0
    message: |
      Изображение не может быть обработано из-за сильной недодержки. 
      Пожалуйста, повторите сканирование с увеличенной яркостью.

contrast:
  high:
    values:
      contrast_ratio: 0.5
      dark_ratio: 0.13
      light_ratio: 0.9
    message: |
      Изображение имеет критически низкий контраст.
      Примените адаптивное выравнивание гистограммы (CLAHE) или локальную коррекцию контраста.
  medium:
    values:
      contrast_ratio: 0.5
      dark_ratio: 0.26
      light_ratio: 0.8
    message: |
      Изображение имеет сниженный контраст.
      Рекомендуется применить коррекцию уровней с растягиванием гистограммы по всему динамическому диапазону.
  low:
    values:
      contrast_ratio: 0.5
      dark_ratio: 0.208
      light_ratio: 0.7
    message: |
      Изображение имеет умеренный контраст.
      Рекомендуется применить небольшую коррекцию контраста с параметром alpha=1.2.
  not_usable:
    values:
      contrast_ratio: 0.0
      dark_ratio: 0.0
      light_ratio: 0.0
    message: |
      Изображение не может быть обработано из-за сильного низкого контраста. 
      Пожалуйста, повторите сканирование с улучшенной освещенностью.